### ISSUE TITLE
Panic, channel capacity must be positive

### ISSUE THREAD

**Issue by dignifiedquire** [async-rs/stop-token#1]
https://github.com/async-rs/stop-token/blob/master/src/lib.rs#L104 panics, because the current `channel` implmentation requires a capacity `>0`

**Comment by matklad** [comment]
Wow, who would have thought that "run each line of code at least once" rule of thumb applies when you publish a library :rofl:

**Comment by matklad** [comment]
Fixed in the latest master and published as `0.1.1`, thanks!

**Comment by dignifiedquire** [comment]
I don't think that version is published yet

**Comment by matklad** [comment]
Published for real this time: https://crates.io/crates/stop-token
