### ISSUE TITLE
Documentation is broken for stop-token-0.1.2

### ISSUE THREAD

**Issue by GWBasic** [async-rs/stop-token#6]
When I visit https://docs.rs/crate/stop-token/0.1.2, I see "docs.rs failed to build stop-token-0.1.2

![Screen Shot 2020-12-07 at 10 25 05 AM](https://user-images.githubusercontent.com/156124/101369576-7bd84700-3876-11eb-939c-dfcd8ae9dab8.png)
"

**Comment by flub** [comment]
This should have been fixed in version 0.2 (https://crates.io/crates/stop-token/0.2.0) now that #7 is merged.
